name: CI
on:
    push:
    merge_group:
    pull_request:
jobs:
    fmt-check:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: software-mansion/setup-scarb@v1
              with:
                  scarb-version: "0.7.0"
            - run: for dir in ./examples/* ; do cd $dir && scarb fmt --check && cd ../..; done;
    sozo-test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - run: curl -L https://install.dojoengine.org | bash
            - run: /home/runner/.config/.dojo/bin/dojoup
            - run: for dir in ./examples/* ; do cd $dir && /home/runner/.config/.dojo/bin/sozo build && /home/runner/.config/.dojo/bin/sozo test && cd ../..; done;
